### ISSUE TITLE
Increase hitlistObjectsLimit to 100

### ISSUE THREAD

**Issue by piejanssens** [wozjac/vscode-ui5-api-reference#5]
25 is too limited: e.g. search for 'button'
I would increase the limit to 100

**Comment by wozjac** [comment]
Hi,

actually I'm working on making this configurable; soon come.

BR,
Jacek

**Comment by wozjac** [comment]
Delivered in [v1.4.0](https://github.com/wozjac/vscode-ui5-api-reference/releases/tag/v1.4.0 ).
